### PR TITLE
add option to set kafka's StartOffset on the consumer

### PR DESCRIPTION
**Pull request by JohnRoesler**
### Description

Exposes a new method `WithStartOffset` using the Option on the EventBus allowing users to configure where to start the consumer

### Affected Components

- Event Bus, Event Store etc

### Related Issues

#339 

### Solution and Design

I followed the pattern using the Option type similar to WithCodec

### Steps to test and verify

1. Added a unit test to verify the option is set properly

How do you feel about the stretchr testify package? I can remove that for the test assertions if you'd prefer.

### CODE REVIEW

**Comment by maxekman** [comment]
Nice PR! I approved running on CI. Please rebase and take a look at the tests and we can merge it.

**Comment by maxekman** [comment]
Yeah, flag as integration. Look at the other integration tests for how. 👍

**Comment by maxekman** [comment]
Thanks for the contribution!

**Comment by JohnRoesler** [comment]
You're welcome. I appreciate the library 👍

**Pull request merged**
