### PR TITLE
Add RemoveObserver on EventBus interface, allows for httputils to remove once handled.

### LINKED ISSUE #187: Possible memory leak in httputils.EventBusHandler
I'm not to sure but `httputils.EventBusHandler` adds an observer to event publisher but never removes it after the request has ended.

https://github.com/looplab/eventhorizon/blob/master/httputils/eventbus.go

### PR DESCRIPTION
**Pull request by bweston92**
Fixes #187

### CODE REVIEW

**Comment by maxekman** [comment]
Looks like a good addition. The mocks needs to be updated too, check the CI logs.

**Comment by maxekman** [comment]
Hi @bweston92, I can merge this after you rebase and fix the issue with the mocks if you want. Thanks.

**Comment by maxekman** [comment]
I'll close this as the affected interfaces and implementations has changed a lot. Feel free to re-open or file an issue.

**Comment by bweston92** [comment]
Has the actual memory leak been sorted in master?

**Pull request closed without merging**
