### PR TITLE
254 / Save and publish events atomically

### LINKED ISSUE #254: Save & publish event atomically
What happens if a failure occurs between the time an event is saved to the event store and that event is published to the bus? According to this source code, it seems these operations aren't atomic, are they?

https://github.com/looplab/eventhorizon/blob/8ae04a04ec8f95a7db77d28a0fab5b563a7e2dc3/aggregatestore/events/aggregatestore.go#L142-L157

### PR DESCRIPTION
**Pull request by maxekman**
### Description

Save and publish events atomically by wrapping them in a transaction.

### Affected Components

- Event Bus (both memory and MongoDB)
- Event Store (both memory and MongoDB)

### Related Issues

Fixes #254.

### Solution and Design

Uses MongoDB (and in-memory simulated) transactions to only commit events to the event store after publishing has been successful.

### CODE REVIEW

**Comment by maxekman** [comment]
@maarek and @giautm Any input on this approach?

**Comment by giautm** [comment]
Hi, sorry for delay.

I don't think move publish progress to transaction is the solution. Because It cause new two problems:
- If the publish progress too long - network delay for example, then the database will lock until the publish success/failed.
- In case the publish success, commit transaction maybe failure. Then, other services will receive the "ghost-events" (Events that's not happened on the source).

**Comment by maxekman** [comment]
Thanks @giautm for the input. I believe you are correct! Maybe some kind of outbox pattern is the way to go then..

**Comment by maxekman** [comment]
Closing until further work has been done on this (probably the outbox pattern).

**Pull request closed without merging**
