### PR TITLE
Pass the original aggregate version to EventStore.Save(), for issue #16

### PR DESCRIPTION
**Pull request by maxekman**
The original aggregate version is used for checking that a save can only be done if the version of the
aggregate has not been changed since it was loaded.

### CODE REVIEW

**Comment by grillbiff** [comment]
I'm not seeing any actual version checking going on (only been looking in the memory event store) in `Save`

Maybe something like this?

```
if len(events) == 0 {
  return eventhorizon.ErrNoEventsToAppend
}

if a, ok := s.aggregateRecords[events[0].AggregateID()]; ok && a.Version() != originalVersion {
  return eventhorizon.ErrAggregateVersionConflict
}
```

**Comment by maxekman** [comment]
Yes, the version is currently not used in the memory event store. I should have added it to this PR, will update later. 

Please check the MongoDB event store, the memory store is mainly for testing and dev (but should be updated nonetheless!).

The DynamoDB event store is still very much alpha, but you can have a look if you want.

**Comment by maxekman** [comment]
@grillbiff I have added the version checking to the memory event store now. If you have time you can take a look.

**Comment by grillbiff** [comment]
looks good to me. We decided to roll our own framework (for learning purposes) and our solution looks similar. Still very interested in keeping in touch and discussing issues with cqrs/es

**Comment by maxekman** [comment]
Thanks. Yes, lets keep in touch. EH will be developed on a lot this fall as I have an opportunity to work on it for a client. If you change your mind and want to use EH I'm more than willing to discuss your needs to see if they align and how it can be useful for both of us!

**Pull request merged**
