### PR TITLE
Remove RegisterCommand

### PR DESCRIPTION
**Pull request by chriskolenko**
Doesn't look like the following is used anymore
```
eh.RegisterCommand(func() eh.Command { ... })
```

This PR is to remove it.

### CODE REVIEW

**Comment by maxekman** [comment]
Well spotted, but we do use that part of the API in our app code, mainly for creating concrete commands from HTTP requests. I could definitely see this packaged in a separate module instead of the main package though!

**Comment by maxekman** [comment]
I would like to add a HTTP command input at some point to do what we do, which would most certainly need this functionality.

**Comment by maxekman** [comment]
I would love to merge this as a split to its own package to minimise the main API surface!

**Comment by chriskolenko** [comment]
Do you have an example of how you using it? Sounds very interesting. 

I've been looking for better examples of ES so I can validate what I'm doing is correct.

**Comment by maxekman** [comment]
Sure, here is something similar to what we use, although simplified (have not tested it):

```
func PostCommand(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// Parse and check the ID in the URL.
	id, ok := parseID(w, r)
	if !ok {
	    w.WriteHeader(http.StatusBadRequest)
	    w.Write("could not get ID: " + err.Error())
		return
	}

	// Get the command type registered for the URL.
	parts := strings.Split(r.URL.Path, "/")
	name := parts[len(parts)-1]
	commandType, ok := commandTypeByName[name]
	if !ok {
	    w.WriteHeader(http.StatusInternalServerError)
	    w.Write("command name not registered: " + err.Error())
        return
	}

	// Create a command instance.
	cmd, err := eh.CreateCommand(commandType)
	if err != nil {
	    w.WriteHeader(http.StatusInternalServerError)
	    w.Write("command type not registered: " + err.Error())
        return
	}

    // Parse the JSON into it.
	decoder := json.NewDecoder(r.Body)
	err := decoder.Decode(&cmd)
	if err != nil {
	    w.WriteHeader(http.StatusBadRequest)
	    w.Write("could not parse command: " + err.Error())
        return
    }

	// Set the command ID from the URL.
	if settable, ok := cmd.(IDSettable); ok {
		settable.SetID(id)
	} else {
	    w.WriteHeader(http.StatusInternalServerError)
	    w.Write("could not set ID on command")
        return
	}

	if err := commandBus.HandleCommand(ctx, cmd); err != nil {
	    w.WriteHeader(http.StatusBadRequest)
	    w.Write("could not execute command: " + err.Error())
        return
	}

    w.WriteHeader(StatusOK)
}
```

**Comment by maxekman** [comment]
I created #149 to track that.

**Comment by chriskolenko** [comment]
Feels like you're looking for a simple IoC implementation. 

Did you want me to make any changes to this PR to get it over the line? or should we close it?

**Comment by maxekman** [comment]
Yeah, either that or a command builder from JSON which would be used in the handlers in client code.

Sure, it would be great if you would like to move the command creation functionality into a package called for example `commandregistry` or `commandfactory`. We still get the benefit of a smaller core API surface as I wrote above.

**Comment by maxekman** [comment]
Method names could then be changed to `Register`, `Unregister` and `New` to simplify further.

But if you don't have the time I can add an issue for it to do later instead.

**Comment by chriskolenko** [comment]
Closing this. Will investigate at a later date.

**Pull request closed without merging**
