### PR TITLE
ISSUE-190 / Use globalsign/mgo instead of labix/mgo as MongoDB driver

### LINKED ISSUE #190: [mongodb] Use maintained driver
Current MongoDB driver has been deprecated a while, whilst there is some forks which are maintained not everyone uses the same.

However I have just seen that MongoDB now have an official driver: https://github.com/mongodb/mongo-go-driver

Thoughts?

### PR DESCRIPTION
**Pull request by maxekman**
# Summary
Minmal changes to switch driver, should provide better performance.

# How to test

# Issue

Fixes #190.

# Notes

### CODE REVIEW

**Comment by bweston92** [comment]
Can you tag a release for the commit before this PR and then a new release for this PR commit? For the people who have legacy projects still using old version of mgo.

**Comment by bweston92** [comment]
Thanks, I mainly suffered because of https://github.com/looplab/eventhorizon/blob/master/eventstore/mongodb/eventstore.go#L70

**Comment by bweston92** [comment]
You wouldn't use versions? `v0.1.0` before and `v0.2.0` after? Then when you split it out can go with `v0.3.0` until stable and start using `v1.0.0`

**Comment by maxekman** [comment]
Yeah, I should have started with that some time ago actually... Maybe I should start now.

**Comment by maxekman** [comment]
Done and dusted! Check the releases page if you are interested.

**Comment by bweston92** [comment]
Thanks :) and it is sure a good time to start when I can see a lot of changes coming up with splitting out

**Comment by maxekman** [comment]
Yup, thanks for encouraging me. 😊

**Pull request merged**
